version: '3.1'

services:
    messagebus:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:15672
            - 5672:5672
        # environment:
        #     ENV_EXAMPLE_VAR_1: ${ENV_EXAMPLE_VAR_1}
        # volumes:
        #     - ./volumes/prod.conf:/etc/rabbitmq/rabbitmq.conf
        networks:
            - bimshirestore-dev
networks:
    bimshirestore-dev:
